USING [DB_OPCCIEL2]
GO

INSERT INTO [DB_OPCCIEL2].[Titre].[TJ_CoursTitre]
([dateCours]
,[idTitre]
,[coursVeille]
,[ouverture]
,[haut]
,[bas]
,[coursSeance]
,[variation]
,[nbreTrans]
,[volTransiger]
,[valTransiger]
,[resteOffre]
,[resteDemande]
,[coursReference]
,[estValider]
,[dateCreationServeur]
,[dateDernModifServeur]
,[dateDernModifClient]
,[userLogin]
,[numLigne]
,[supprimer]
,[rowvers]
,[estVerifie1]
,[dateVerification1]
,[userLoginVerificateur1]
,[estVerifie2]
,[dateVerification2]
,[userLoginVerificateur2]
)
SELECT [dateCours]
     ,t.[idTitre]
     ,[coursVeille]
     ,[ouverture]
     ,[haut]
     ,[bas]
     ,[coursSeance]
     ,[variation]
     ,[nbreTrans]
     ,[volTransiger]
     ,[valTransiger]
     ,[resteOffre]
     ,[resteDemande]
     ,[coursReference]
     ,[estValider]
     ,[dateCreationServeur]
     ,[dateDernModifServeur]
     ,[dateDernModifClient]
     ,[userLogin]
     ,[numLigne]
     ,[supprimer]
     ,[rowvers]
     ,[estVerifie1]
     ,[dateVerification1]
     ,[userLoginVerificateur1]
     ,[estVerifie2]
     ,[dateVerification2]
     ,[userLoginVerificateur2]
FROM [DB_TITRESCIEL].[Titre].[TJ_CoursTitre] ct
INNER JOIN [DB_OPCCIEL2].[Titre].[T_Titre] t
    ON t.idOcc = ct.idTitre
GO

INSERT INTO [DB_OPCCIEL2].[Titre].[T_TableauAmortissement]
([idTitre]
,[numeroEcheance]
,[dateEcheance]
,[tauxAmortissement]
,[nombreTitre]
,[capital]
,[interet]
,[nombreTitreAmorti]
,[montantRembourse]
,[annuiteTotale]
,[montantFinPeriode]
,[estGenere]
,[numLigne]
,[dateCreationServeur]
,[dateDernModifClient]
,[dateDernModifServeur]
,[userLogin]
,[supprimer]
,[rowvers])
SELECT t.[idTitre]
     ,[numeroEcheance]
     ,[dateEcheance]
     ,[tauxAmortissement]
     ,[nombreTitre]
     ,[capital]
     ,[interet]
     ,[nombreTitreAmorti]
     ,[montantRembourse]
     ,[annuiteTotale]
     ,[montantFinPeriode]
     ,[estGenere]
     ,tab.[numLigne]
     ,tab.[dateCreationServeur]
     ,tab.[dateDernModifClient]
     ,tab.[dateDernModifServeur]
     ,tab.[userLogin]
     ,tab.[supprimer]
     ,tab.[rowvers]
FROM [DB_TITRESCIEL].[Titre].[T_TableauAmortissement] tab
         INNER JOIN [DB_OPCCIEL2].[Titre].[T_Titre] t
                    ON t.idOcc = tab.idTitre
GO
--DELETE FROM [DB_OPCCIEL2].[Titre].[TJ_CoursTitre]
--DELETE FROM [DB_OPCCIEL2].[Titre].[T_TableauAmortissement]


