package com.ged.projection;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public interface DepotRachatTransfertProjection {
    Long getIdOperation() ;
    Long getIdDepotRachat() ;
    String getReferencePiece();
    LocalDateTime getDateOperation();
    String getNomSigle();
    String getPrenomRaison();
    BigDecimal getMontantDepose();
    BigDecimal getMontantSouscrit();
    BigDecimal getQtePart();
    Long getIdSeance();
    String getIdActionnaire();
    Long getIdOpcvm();
    String getDenominationOpcvm();
    LocalDateTime getDateOuv();
    LocalDateTime getDateFerm();
    String getIdPersonne();
    String getDistributeur();
    boolean isEstVerifie1();
    boolean isEstVerifier();
    LocalDateTime getDateVerification1();
    String getUserLoginVerificateur1();
    boolean isEstVerifie2();
    LocalDateTime getDateVerification2();
    String getUserLoginVerificateur2();
    Long getIdTitre();
    BigDecimal getQte();
    BigDecimal getCours();
    BigDecimal getCommission();
    BigDecimal getInteretCouru();
    BigDecimal getInteretPrecompte();
    String getSymbolTitre();
    Long getIdTransaction();
    String getCodeNatureOperation();
    String getLibelleNatureOperation();
    String getLibelleOperation();
    LocalDateTime getDateSaisie();
    LocalDateTime getDatePiece();
    LocalDateTime getDateValeur();
    BigDecimal getMontant();
    BigDecimal getQuantite();
    String getEcriture();
    Boolean getEstOD();
    String getType();
    String getModeVL();
    boolean isEstGenere();
    String getNomVerificateur();
    LocalDateTime getDateVerification();
    String getUserLogin();
    Boolean getSupprimer();
    String getDesignationTitre();
	String getPersonne();
}
