### LOGIN TO THE APPLICATION
POST http://localhost:8181/opcciel/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user1"
}

> {% client.global.set("auth-token", response.body.data.authToken); %}

### GET USER BY TOKEN
GET http://localhost:8181/opcciel/api/auth/me
Content-Type: application/json
Authorization: Bearer {{ auth-token }}

### GET ALL MENUS
GET http://localhost:8181/opcciel/api/admin/menus
Content-Type: application/json
Authorization: Bearer {{ auth-token }}